// Shared primitives + data for SZCZ Softwares terminal portfolio

// i18n helper: pick `${base}_${lang}` with fallback to en/fr.
const tx = (obj, base, lang) =>
  (obj && (obj[`${base}_${lang}`] ?? obj[`${base}_en`] ?? obj[`${base}_fr`])) || "";

const PROJECTS = [
  {
    slug: "susumou",
    title: "Susumou",
    tagline_fr: "Apprendre le japonais — Flutter + SRS + Gemini, JLPT N5→N1",
    tagline_en: "Learn Japanese — Flutter + SRS + Gemini, JLPT N5→N1",
    tagline_ja: "日本語学習アプリ — Flutter + SRS + Gemini、JLPT N5〜N1対応",
    summary_fr: "App mobile d'apprentissage du japonais : SRS (répétition espacée), dictionnaire offline, explications générées par Gemini AI, parcours adaptés aux niveaux JLPT N5 à N1.",
    summary_en: "Mobile Japanese-learning app: SRS (spaced repetition), offline dictionary, Gemini-AI-generated explanations, paths tailored to JLPT N5 through N1.",
    summary_ja: "日本語学習モバイルアプリ：SRS（間隔反復）、オフライン辞書、Gemini AIによる文脈解説、JLPT N5からN1までのレベル別カリキュラム。",
    tags: ["Flutter", "Firebase", "Gemini AI", "SRS"],
    status: "Beta",
    year: "2025",
    category: "mobile",
    stores: { ios: "soon", android: "soon" },
    highlights_fr: ["Dictionnaire offline 170k entrées", "SRS adaptatif à l'utilisateur", "Explications IA contextuelles"],
    highlights_en: ["Offline dictionary, 170k entries", "User-adaptive SRS", "Contextual AI explanations"],
    highlights_ja: ["17万語のオフライン辞書", "ユーザーに適応するSRS", "文脈に応じたAI解説"],
    legal: [
      { id: "privacy", fr: "Politique de confidentialité", en: "Privacy policy", ja: "プライバシーポリシー" },
      { id: "cgu", fr: "CGU", en: "Terms of use", ja: "利用規約" },
      { id: "cgv", fr: "CGV", en: "Terms of sale", ja: "販売条件" },
      { id: "mentions-legales", fr: "Mentions légales", en: "Legal notice", ja: "法的事項" },
      { id: "account-deletion", fr: "Suppression de compte", en: "Account deletion", ja: "アカウント削除" },
    ],
  },
  {
    slug: "soccer-link",
    title: "Soccer Link",
    tagline_fr: "Football amateur — réseau Flutter pour clubs, joueurs & coachs",
    tagline_en: "Amateur football — Flutter network for clubs, players & coaches",
    tagline_ja: "アマチュアサッカー — クラブ・選手・コーチをつなぐFlutterネットワーク",
    summary_fr: "Réseau social pour le football amateur : profils joueur/coach/club, matchs, stats perso, recherche Algolia, état global Riverpod, notifications Firebase.",
    summary_en: "Social network for amateur football: player/coach/club profiles, matches, personal stats, Algolia search, Riverpod state, Firebase notifications.",
    summary_ja: "アマチュアサッカー向けSNS：選手/コーチ/クラブのプロフィール、試合、個人スタッツ、Algolia検索、Riverpodによる状態管理、Firebase通知。",
    tags: ["Flutter", "Firebase", "Algolia", "Riverpod"],
    status: "Beta",
    year: "2025",
    category: "mobile",
    stores: { ios: "soon", android: "soon" },
    highlights_fr: ["Recherche Algolia < 50ms", "Profils multi-rôles", "Stats perso agrégées"],
    highlights_en: ["Algolia search < 50ms", "Multi-role profiles", "Aggregated personal stats"],
    highlights_ja: ["Algolia検索50ms未満", "複数ロール対応プロフィール", "個人スタッツ集計"],
    legal: [
      { id: "privacy", fr: "Politique de confidentialité", en: "Privacy policy", ja: "プライバシーポリシー" },
      { id: "cgu", fr: "CGU", en: "Terms of use", ja: "利用規約" },
      { id: "cgv", fr: "CGV", en: "Terms of sale", ja: "販売条件" },
      { id: "mentions-legales", fr: "Mentions légales", en: "Legal notice", ja: "法的事項" },
      { id: "account-deletion", fr: "Suppression de compte", en: "Account deletion", ja: "アカウント削除" },
    ],
  },
  {
    slug: "seditio",
    title: "Seditio",
    tagline_fr: "Roguelite tactique — Godot, IA ennemie, boucle économique",
    tagline_en: "Tactical roguelite — Godot, enemy AI, economy loop",
    tagline_ja: "タクティカル・ローグライト — Godot、敵AI、経済ループ",
    summary_fr: "Jeu indé solo : exploration tactique au tour-par-tour dans un monde post-effondrement, avec une IA ennemie scriptée en GDScript et une boucle économique qui récompense la prise de risque.",
    summary_en: "Solo indie game: turn-based tactical exploration in a post-collapse world, with GDScript-driven enemy AI and an economy loop that rewards risk-taking.",
    summary_ja: "ソロ制作のインディーゲーム：崩壊後の世界を舞台にしたターン制タクティカル探索。GDScriptで動く敵AIと、リスクを取るほど報われる経済ループを特徴とする。",
    tags: ["Godot", "GDScript", "Game Design", "AI"],
    status: "WIP",
    year: "2025",
    category: "games",
    stores: { desktop: "soon" },
    highlights_fr: ["Prototype jouable 3 niveaux", "IA ennemie à utilité + mémoire", "Système de craft et scoring"],
    highlights_en: ["Playable 3-level prototype", "Utility + memory enemy AI", "Craft and scoring system"],
    highlights_ja: ["3レベル分のプレイ可能なプロトタイプ", "効用＋記憶ベースの敵AI", "クラフト＆スコアリングシステム"],
    legal: [],
  },
  {
    slug: "sakidori",
    title: "SakiDori",
    tagline_fr: "Tracker marchés — Flutter + API Finance, notifs, charts",
    tagline_en: "Market tracker — Flutter + Finance API, notifications, charts",
    tagline_ja: "市場トラッカー — Flutter + 金融API、通知、チャート",
    summary_fr: "Application mobile pour suivre des paniers d'actions, crypto et indices avec des alertes personnalisées sur variations et seuils. UI dense, charts fluides, mode hors-ligne.",
    summary_en: "Mobile app to track stock, crypto and index baskets with custom alerts on variations and thresholds. Dense UI, smooth charts, offline mode.",
    summary_ja: "株式・暗号資産・指数のバスケットを追跡するモバイルアプリ。変動率や閾値に応じたカスタムアラート、密度の高いUI、なめらかなチャート、オフラインモード対応。",
    tags: ["Flutter", "Mobile", "Charts", "Notifications"],
    status: "WIP",
    year: "2025",
    category: "mobile",
    stores: { ios: "soon", android: "soon" },
    highlights_fr: ["Alertes push sur conditions custom", "Mode offline avec cache intelligent", "Charts 60fps sur 5000 points"],
    highlights_en: ["Push alerts on custom conditions", "Offline mode with smart cache", "60fps charts over 5000 points"],
    highlights_ja: ["カスタム条件のプッシュ通知", "スマートキャッシュ付きオフラインモード", "5000点で60fpsのチャート"],
    legal: [],
  },
  {
    slug: "billiard-tracker",
    title: "Billiard Tracker",
    tagline_fr: "ELO & stats — app web locale pour billard, classement live",
    tagline_en: "ELO & stats — local web app for billiards, live ranking",
    tagline_ja: "ELOとスタッツ — ビリヤード用ローカルWebアプリ、ライブランキング",
    summary_fr: "Système de suivi et classement ELO pour billard. App web servie en réseau local, interface tactile pour la table, score en direct, historique et rematchs.",
    summary_en: "ELO tracking and ranking system for billiards. Web app served on local network, table-side touch UI, live score, history and rematches.",
    summary_ja: "ビリヤード向けのELO追跡・ランキングシステム。ローカルネットワーク上で動作するWebアプリ、テーブル横で使えるタッチUI、ライブスコア、履歴、再戦機能。",
    tags: ["PWA", "WebSocket", "React", "Node.js"],
    status: "Live",
    year: "2024",
    category: "web",
    stores: {},
    highlights_fr: ["App web tactile en réseau local", "Synchro temps réel via WebSocket", "Historique 500+ parties"],
    highlights_en: ["Touch web app on local network", "Real-time sync via WebSocket", "History of 500+ matches"],
    highlights_ja: ["ローカルネットワーク向けタッチWebアプリ", "WebSocketによるリアルタイム同期", "500試合以上の履歴"],
    legal: [],
  },
];

const SERVICES = [
  { id: "web", cmd: "web --build", fr: "Sites & apps web", en: "Web sites & apps", ja: "Webサイト・アプリ", desc_fr: "Next.js / React, PWA, SEO, intégrations API, auth & paiements.", desc_en: "Next.js / React, PWA, SEO, API integrations, auth & payments.", desc_ja: "Next.js / React、PWA、SEO、API連携、認証・決済。" },
  { id: "mobile", cmd: "mobile --ship", fr: "Apps mobiles", en: "Mobile apps", ja: "モバイルアプリ", desc_fr: "Flutter iOS/Android, notifs, stockage local/cloud, charts.", desc_en: "Flutter iOS/Android, notifications, local/cloud storage, charts.", desc_ja: "Flutter iOS/Android、通知、ローカル/クラウドストレージ、チャート。" },
  { id: "ai", cmd: "ai --augment", fr: "IA & automatisation", en: "AI & automation", ja: "AI・自動化", desc_fr: "RAG/embeddings, copilotes, pipelines, FastAPI, scripts.", desc_en: "RAG/embeddings, copilots, pipelines, FastAPI, scripts.", desc_ja: "RAG/エンベディング、コパイロット、パイプライン、FastAPI、スクリプト。" },
  { id: "chain", cmd: "chain --deploy", fr: "Blockchain & NFT", en: "Blockchain & NFT", ja: "ブロックチェーン・NFT", desc_fr: "Contrats simples, proof-of-ownership, mint portals.", desc_en: "Simple contracts, proof-of-ownership, mint portals.", desc_ja: "シンプルなコントラクト、所有権証明、ミントポータル。" },
  { id: "games", cmd: "games --prototype", fr: "Jeux vidéo", en: "Video games", ja: "ビデオゲーム", desc_fr: "Prototypes Godot, gameplay, UX/UI, builds desktop/mobile.", desc_en: "Godot prototypes, gameplay, UX/UI, desktop/mobile builds.", desc_ja: "Godotプロトタイプ、ゲームプレイ、UX/UI、デスクトップ/モバイル向けビルド。" },
  { id: "tools", cmd: "tools --dashboard", fr: "Outils & dashboards", en: "Tools & dashboards", ja: "ツール・ダッシュボード", desc_fr: "Electron/PWA, dashboards temps réel, WebSockets, IoT.", desc_en: "Electron/PWA, real-time dashboards, WebSockets, IoT.", desc_ja: "Electron/PWA、リアルタイムダッシュボード、WebSocket、IoT。" },
];

const STACK = [
  { g: "Frontend", items: ["TypeScript", "Next.js", "React", "Flutter / Dart", "Riverpod"] },
  { g: "Backend", items: ["Python", "FastAPI", "Node.js", "PostgreSQL", "Firebase"] },
  { g: "AI / Data", items: ["LLM / RAG", "pgvector", "Embeddings", "Gemini", "OpenAI"] },
  { g: "Other", items: ["Godot", "Solidity", "Docker", "GitHub Actions", "Raspberry Pi"] },
];

const STATS = [
  { value: "10", label_fr: "projets produits", label_en: "products built", label_ja: "完成プロダクト" },
  { value: "3", label_fr: "apps en cours", label_en: "apps in progress", label_ja: "進行中のアプリ" },
  { value: "2", label_fr: "jeux en projet", label_en: "games planned", label_ja: "計画中のゲーム" },
  { value: "10+", label_fr: "années à coder", label_en: "years coding", label_ja: "コーディング歴" },
];

// i18n copy
const COPY = {
  fr: {
    nav: { home: "accueil", work: "projets", services: "services", stack: "stack", about: "à propos", contact: "contact", legal: "mentions" },
    hero_title: ["Je construis des produits", "web, mobile, IA et jeux."],
    hero_sub: "Un dev indépendant qui livre — de l'idée au déploiement. Web, mobile, IA (LLM/RAG), blockchain et jeux indés.",
    cta_primary: "Discutons de votre projet",
    cta_secondary: "Voir les projets",
    sections: { work: "Projets sélectionnés", services: "Services", stack: "Stack & expertise", about: "À propos", contact: "Contact" },
    status_open: "disponible pour missions",
    location: "Nantes · Paris · Tokyo",
    back: "retour",
    overview: "Vue d'ensemble",
    highlights: "Points forts",
    stack_label: "Stack",
    more_projects: "Autres projets",
    legal_documents: "Documents légaux",
    contact_open: "Ouvert aux missions",
    contact_sub: "Basé en France. Remote, déplacements en Europe & Japon.",
    contact_placeholder_name: "Votre nom",
    contact_placeholder_email: "Votre e-mail",
    contact_placeholder_msg: "Parlez-moi de votre projet…",
    contact_send: "envoyer",
    contact_ok: "Message envoyé. Je reviens vers vous sous 48h.",
    contact_new_message: "nouveau message",
    contact_availability: "disponibilité",
    contact_channels: "canaux",
    contact_response: "temps de réponse",
    checklist: ["Approche lean orientée valeur", "Design clean & accessible", "Data-driven, KPI clairs", "Livrables testés & documentés"],
    bio: "Je m'appelle Bastian. Je code depuis plus de 10 ans et je livre des produits complets — du pitch au déploiement. J'aime les problèmes concrets, les contraintes réelles et les boucles d'itération courtes.",
    status_label: "statut",
    year_label: "année",
    category_label: "catégorie",
    privacy_title: "Politique de confidentialité",
    legal_title: "Mentions légales",
    made_in: "Conçu & codé à Nantes",
  },
  en: {
    nav: { home: "home", work: "work", services: "services", stack: "stack", about: "about", contact: "contact", legal: "legal" },
    hero_title: ["I ship web, mobile,", "AI and game products."],
    hero_sub: "An independent dev who delivers — from idea to deployment. Web, mobile, AI (LLM/RAG), blockchain, and indie games.",
    cta_primary: "Let's talk about your project",
    cta_secondary: "See the work",
    sections: { work: "Selected work", services: "Services", stack: "Stack & expertise", about: "About", contact: "Contact" },
    status_open: "open for work",
    location: "Nantes · Paris · Tokyo",
    back: "back",
    overview: "Overview",
    highlights: "Highlights",
    stack_label: "Stack",
    more_projects: "Other projects",
    legal_documents: "Legal documents",
    contact_open: "Open for work",
    contact_sub: "Based in France. Remote, travel in Europe & Japan.",
    contact_placeholder_name: "Your name",
    contact_placeholder_email: "Your email",
    contact_placeholder_msg: "Tell me about your project…",
    contact_send: "send",
    contact_ok: "Message sent. I'll get back to you within 48h.",
    contact_new_message: "new message",
    contact_availability: "availability",
    contact_channels: "channels",
    contact_response: "response time",
    checklist: ["Lean, value-first approach", "Clean, accessible design", "Data-driven, clear KPIs", "Tested, documented deliverables"],
    bio: "I'm Bastian. I've been coding for over 10 years and I ship complete products — from pitch to deployment. I enjoy concrete problems, real constraints, and short iteration loops.",
    status_label: "status",
    year_label: "year",
    category_label: "category",
    privacy_title: "Privacy policy",
    legal_title: "Legal notice",
    made_in: "Designed & coded in Nantes",
  },
  ja: {
    nav: { home: "ホーム", work: "実績", services: "サービス", stack: "技術", about: "自己紹介", contact: "お問い合わせ", legal: "法的事項" },
    hero_title: ["ウェブ・モバイル・", "AI・ゲームを作ります。"],
    hero_sub: "アイデアから本番リリースまで届ける独立系開発者です。Web、モバイル、AI（LLM/RAG）、ブロックチェーン、インディーゲームを手がけます。",
    cta_primary: "プロジェクトについて相談する",
    cta_secondary: "実績を見る",
    sections: { work: "セレクトプロジェクト", services: "サービス", stack: "技術スタック", about: "自己紹介", contact: "お問い合わせ" },
    status_open: "現在お仕事受付中",
    location: "ナント・パリ・東京",
    back: "戻る",
    overview: "概要",
    highlights: "ハイライト",
    stack_label: "スタック",
    more_projects: "他のプロジェクト",
    legal_documents: "法的書類",
    contact_open: "お仕事受付中",
    contact_sub: "フランス在住。リモート可、欧州・日本へ出張対応。",
    contact_placeholder_name: "お名前",
    contact_placeholder_email: "メールアドレス",
    contact_placeholder_msg: "プロジェクトについて教えてください…",
    contact_send: "送信",
    contact_ok: "メッセージを送信しました。48時間以内にご返信します。",
    contact_new_message: "新しいメッセージ",
    contact_availability: "対応状況",
    contact_channels: "連絡手段",
    contact_response: "返信時間",
    checklist: ["価値重視のリーン開発", "クリーンでアクセシブルなデザイン", "データドリブン、明確なKPI", "テスト・ドキュメント完備"],
    bio: "バスチャンと申します。10年以上コードを書き続け、ピッチからデプロイまでプロダクトを完成させてきました。具体的な課題、現実の制約、短いイテレーションサイクルが好きです。",
    status_label: "ステータス",
    year_label: "年",
    category_label: "カテゴリ",
    privacy_title: "プライバシーポリシー",
    legal_title: "法的事項",
    made_in: "ナントで設計・開発",
  },
};

// ============ Primitives ============

const Cursor = () => <span className="blink">▍</span>;

const Prompt = ({ children, user = "bastian", host = "szcz" }) => (
  <span className="prompt">
    <span className="prompt-user">{user}</span>
    <span className="prompt-at">@</span>
    <span className="prompt-host">{host}</span>
    <span className="prompt-colon">:</span>
    <span className="prompt-path">~</span>
    <span className="prompt-dollar">$</span>
    <span className="prompt-cmd"> {children}</span>
  </span>
);

const Tag = ({ children, kind = "default" }) => (
  <span className={`tag tag-${kind}`}>{children}</span>
);

const StatusDot = ({ status }) => {
  const map = {
    Live: "status-live",
    Beta: "status-beta",
    WIP: "status-wip",
    Client: "status-client",
    Delivered: "status-delivered",
  };
  return <span className={`status-dot ${map[status] || ""}`} aria-label={status}>●</span>;
};

const AsciiRule = ({ char = "─", label }) => (
  <div className="ascii-rule" aria-hidden={!label}>
    <span className="ascii-rule-line">{char.repeat(120)}</span>
    {label && <span className="ascii-rule-label">[{label}]</span>}
    <span className="ascii-rule-line">{char.repeat(120)}</span>
  </div>
);

const Placeholder = ({ label, aspect = "16 / 10" }) => (
  <div className="placeholder" style={{ aspectRatio: aspect }}>
    <span className="placeholder-label">{label}</span>
  </div>
);

// Category → icon label (text, not SVG)
const CATEGORY_META = {
  games: { label: "GAME", hue: 145 },
  mobile: { label: "MOB", hue: 200 },
  web: { label: "WEB", hue: 260 },
  ai: { label: "AI", hue: 75 },
  blockchain: { label: "CHN", hue: 25 },
};

// Per-project legal doc content (FR + EN). keyed by project slug + doc id.
const PROJECT_LEGAL = {
  "susumou": {
    "privacy": {
      fr: {
        title: "Politique de confidentialité — Susumou (進もう)",
        updated: "Version 1.1 — Dernière mise à jour : 21 mars 2026",
        intro: "La présente politique décrit comment SZCZ Softwares (« Éditeur ») collecte, utilise, stocke et protège les données personnelles des utilisateurs de l'application mobile Susumou, disponible sur iOS et Android. En utilisant l'Application, vous acceptez les pratiques décrites ci-dessous.",
        sections: [
          { h: "1. Éditeur et responsable du traitement", b: "SZCZ Softwares (SASU). Siège social : France. E-mail : contact@szcz-softwares.com." },
          { h: "2. Données collectées", b: "Données de compte (authentification anonyme Firebase, e-mail + mot de passe haché, Google ou Apple Sign-In). Données d'apprentissage (progression, cartes étudiées, statistiques SRS, objectifs, préférences). Données techniques (Firebase Analytics, Crashlytics, Remote Config, App Check — modèle, OS, version). Données d'IA (prompts, niveau, progression transmis à l'API Google Gemini, sans donnée directement identifiante). Stockage local pour performances et mode hors-ligne." },
          { h: "3. Finalités du traitement", b: "Gérer votre compte, synchroniser votre progression, personnaliser les contenus, améliorer l'algorithme SRS, analyser l'utilisation de façon statistique, assurer la sécurité, respecter nos obligations légales." },
          { h: "4. Base légale", b: "Exécution du contrat (fourniture du service), intérêt légitime (amélioration, analyse, sécurité), consentement pour les traitements qui le nécessitent." },
          { h: "5. Partage des données", b: "Vos données ne sont jamais vendues. Partages possibles avec Google / Firebase, Google Gemini, Google AdMob (version gratuite), Apple / Google pour les achats in-app, autorités compétentes en cas d'obligation légale." },
          { h: "6. Transferts internationaux", b: "Certaines données peuvent être hébergées hors UE via les services Google. Des garanties appropriées (clauses contractuelles types, cadres de transfert applicables) sont mises en place conformément au RGPD." },
          { h: "7. Durée de conservation", b: "Compte actif : tant que le compte est actif. Suppression : données supprimées sous 30 jours, sauvegardes sous 90 jours. Inactivité : rappel après 24 mois, archivage possible au-delà de 36 mois." },
          { h: "8. Sécurité", b: "Chiffrement en transit (HTTPS/TLS), authentification Firebase, règles Firestore par utilisateur, App Check, mots de passe hachés." },
          { h: "9. Vos droits (RGPD)", b: "Accès, rectification, suppression, portabilité, opposition, limitation. Contact : contact@szcz-softwares.com. Droit de réclamation auprès de la CNIL (www.cnil.fr)." },
          { h: "10. Données des mineurs", b: "L'Application n'est pas destinée aux moins de 16 ans. Pour signaler des données d'un mineur : contact@szcz-softwares.com." },
          { h: "11. Achats in-app", b: "Transactions gérées par Apple ou Google. Nous ne recevons pas vos données bancaires." },
          { h: "12. Modifications", b: "Nous pouvons mettre à jour cette politique à tout moment. En cas de modification substantielle, une notification est envoyée dans l'Application ou par e-mail." },
          { h: "13. Contact", b: "SZCZ Softwares (SASU), France. E-mail : contact@szcz-softwares.com." },
        ],
      },
      en: {
        title: "Privacy Policy — Susumou (進もう)",
        updated: "Version 1.1 — Last updated: March 21, 2026",
        intro: "This policy describes how SZCZ Softwares (the \"Publisher\") collects, uses, stores and protects personal data of users of the Susumou mobile application, available on iOS and Android. By using the App, you accept the practices described below.",
        sections: [
          { h: "1. Publisher & data controller", b: "SZCZ Softwares (SASU). Registered office: France. Email: contact@szcz-softwares.com." },
          { h: "2. Data collected", b: "Account data (Firebase anonymous auth, email + hashed password, Google or Apple Sign-In). Learning data (progress, studied cards, SRS statistics, goals, preferences). Technical data (Firebase Analytics, Crashlytics, Remote Config, App Check — model, OS, version). AI data (prompts, level, progress sent to the Google Gemini API, with no directly identifying data). Local storage for performance and offline mode." },
          { h: "3. Purposes", b: "Manage your account, sync progress, personalize content, improve the SRS algorithm, analyze usage statistically, ensure security, meet legal obligations." },
          { h: "4. Legal basis", b: "Contract performance (service delivery), legitimate interest (improvement, analysis, security), consent where required." },
          { h: "5. Data sharing", b: "Your data is never sold. Possible sharing with Google / Firebase, Google Gemini, Google AdMob (free version), Apple / Google for in-app purchases, competent authorities in case of legal obligation." },
          { h: "6. International transfers", b: "Some data may be hosted outside the EU via Google services. Appropriate safeguards (standard contractual clauses, applicable transfer frameworks) are in place under the GDPR." },
          { h: "7. Retention", b: "Active account: while the account is active. Deletion: data deleted within 30 days, backups within 90 days. Inactivity: reminder after 24 months, possible archiving after 36 months." },
          { h: "8. Security", b: "In-transit encryption (HTTPS/TLS), Firebase auth, per-user Firestore rules, App Check, hashed passwords." },
          { h: "9. Your rights (GDPR)", b: "Access, rectification, erasure, portability, objection, restriction. Contact: contact@szcz-softwares.com. Right to lodge a complaint with the CNIL (www.cnil.fr)." },
          { h: "10. Minors", b: "The App is not intended for children under 16. To report minor data: contact@szcz-softwares.com." },
          { h: "11. In-app purchases", b: "Transactions handled by Apple or Google. We do not receive your payment details." },
          { h: "12. Updates", b: "We may update this policy at any time. Material changes are notified via the App or by email." },
          { h: "13. Contact", b: "SZCZ Softwares (SASU), France. Email: contact@szcz-softwares.com." },
        ],
      },
      ja: {
        title: "プライバシーポリシー — Susumou（進もう）",
        updated: "バージョン 1.1 — 最終更新日：2026年3月21日",
        intro: "本ポリシーは、SZCZ Softwares（以下「発行者」）が、iOSおよびAndroidで提供するモバイルアプリ「Susumou」の利用者の個人データをどのように収集・利用・保管・保護するかを説明するものです。本アプリをご利用いただくことで、以下の取扱いに同意いただいたものとみなします。",
        sections: [
          { h: "1. 発行者および管理者", b: "SZCZ Softwares（SASU）。本社所在地：フランス。連絡先：contact@szcz-softwares.com。" },
          { h: "2. 収集するデータ", b: "アカウント情報（Firebase匿名認証、メールアドレス＋ハッシュ化パスワード、Google／Apple Sign-In）、学習データ（進捗、学習カード、SRS統計、目標、設定）、技術情報（Firebase Analytics、Crashlytics、Remote Config、App Check — 端末モデル、OS、バージョン）、AIデータ（プロンプト、レベル、進捗をGoogle Gemini APIに送信。直接識別可能な情報は含みません）、パフォーマンスおよびオフラインモードのためのローカルストレージ。" },
          { h: "3. 利用目的", b: "アカウントの管理、進捗の同期、コンテンツのパーソナライズ、SRSアルゴリズムの改善、統計的な利用分析、セキュリティの確保、法令遵守。" },
          { h: "4. 法的根拠", b: "契約の履行（サービス提供）、正当な利益（改善・分析・セキュリティ）、必要な場合の同意。" },
          { h: "5. データの共有", b: "データを販売することは一切ありません。共有の可能性がある相手：Google／Firebase、Google Gemini、Google AdMob（無料版）、アプリ内課金についてはApple／Google、法令上の義務がある場合は管轄当局。" },
          { h: "6. 国外への移転", b: "一部のデータはGoogleのサービスを通じてEU域外で処理される場合があります。GDPRに従い、標準契約条項などの適切な保護措置を講じています。" },
          { h: "7. 保存期間", b: "アクティブなアカウント：アカウントが有効な間。削除：30日以内に削除、バックアップは90日以内。非アクティブ：24か月後にリマインド、36か月超でアーカイブの可能性。" },
          { h: "8. セキュリティ", b: "通信の暗号化（HTTPS/TLS）、Firebase認証、ユーザー単位のFirestoreルール、App Check、パスワードのハッシュ化。" },
          { h: "9. 利用者の権利（GDPR）", b: "アクセス、訂正、削除、ポータビリティ、異議申立、制限の権利。連絡先：contact@szcz-softwares.com。CNIL（www.cnil.fr）への申立も可能です。" },
          { h: "10. 未成年者", b: "本アプリは16歳未満を対象としていません。未成年者のデータを通報するには：contact@szcz-softwares.com。" },
          { h: "11. アプリ内課金", b: "決済はAppleまたはGoogleが処理します。当社は決済情報を受領しません。" },
          { h: "12. ポリシーの変更", b: "本ポリシーは予告なく変更されることがあります。重要な変更はアプリ内またはメールで通知します。" },
          { h: "13. お問い合わせ", b: "SZCZ Softwares（SASU）、フランス。メール：contact@szcz-softwares.com。" },
        ],
      },
    },
    "cgu": {
      fr: {
        title: "Conditions Générales d'Utilisation — Susumou (進もう)",
        updated: "Version 1.1 — Dernière mise à jour : 21 mars 2026",
        intro: "Les présentes CGU régissent l'utilisation de l'application mobile Susumou, éditée par SZCZ Softwares (SASU). En téléchargeant, installant ou utilisant l'Application, vous acceptez sans réserve les présentes CGU.",
        sections: [
          { h: "1. Objet", b: "Susumou (進もう, « Avançons ! ») est une application mobile d'aide à l'apprentissage du japonais combinant flashcards SRS, dictionnaire, leçons JLPT et coach IA." },
          { h: "2. Acceptation", b: "L'utilisation de l'Application implique l'acceptation pleine et entière des CGU. L'utilisateur doit disposer de la capacité juridique nécessaire ; les mineurs doivent obtenir l'autorisation de leur représentant légal." },
          { h: "3. Accès au service", b: "Disponible sur l'App Store et Google Play. L'utilisateur est responsable de la compatibilité de son terminal, de sa connexion et des frais réseau." },
          { h: "4. Compte utilisateur", b: "Authentification possible en mode anonyme, e-mail/mot de passe, Google ou Apple Sign-In. L'utilisateur s'engage à fournir des informations exactes, à protéger ses identifiants et à ne pas partager son compte." },
          { h: "5. Fonctionnalités", b: "Version gratuite avec publicités et version Supporter par abonnement mensuel (suppression des pubs, fonctionnalités IA, avantages premium)." },
          { h: "6. Utilisation de l'IA", b: "Susumou utilise l'API Google Gemini pour le coach IA, la génération de tests, les lectures adaptées et les recommandations. Les prompts et données pédagogiques anonymisées peuvent être transmis. L'utilisateur reconnaît que l'IA peut produire des contenus inexacts." },
          { h: "7. Limites pédagogiques", b: "Susumou est un outil d'aide. Il ne constitue ni un enseignement officiel, ni une certification, ni un substitut à un enseignement professionnel." },
          { h: "8. Comportements interdits", b: "Usage abusif, contournement de sécurité, surcharge serveur, reverse engineering, bots/scripts, partage de compte, exploitation commerciale non autorisée." },
          { h: "9. Suspension / suppression", b: "SZCZ Softwares peut suspendre ou supprimer un compte en cas de violation des CGU. L'utilisateur peut supprimer son compte via les paramètres ou par e-mail." },
          { h: "10. Propriété intellectuelle", b: "L'Application, son design, son code et ses contenus sont la propriété exclusive de SZCZ Softwares. L'utilisateur bénéficie d'une licence d'usage personnelle, non exclusive et révocable." },
          { h: "11. Responsabilité", b: "Service fourni « en l'état ». SZCZ Softwares ne saurait être tenu responsable des interruptions, bugs, erreurs IA ou échecs à un examen." },
          { h: "12. Modification des CGU", b: "Modifications possibles à tout moment. La poursuite de l'utilisation vaut acceptation." },
          { h: "13. Droit applicable", b: "Droit français. Juridictions françaises compétentes, sans préjudice des dispositions impératives consommateur UE." },
          { h: "14. Contact", b: "SZCZ Softwares (SASU), France. E-mail : contact@szcz-softwares.com." },
        ],
      },
      en: {
        title: "Terms of Use — Susumou (進もう)",
        updated: "Version 1.1 — Last updated: March 21, 2026",
        intro: "These Terms of Use govern the use of the Susumou mobile application, published by SZCZ Softwares (SASU). By downloading, installing or using the App, you fully accept these Terms.",
        sections: [
          { h: "1. Purpose", b: "Susumou (進もう, \"Let's move forward!\") is a Japanese-learning mobile app combining SRS flashcards, a dictionary, JLPT lessons and an AI coach." },
          { h: "2. Acceptance", b: "Using the App means full acceptance of the Terms. Users must have the required legal capacity; minors need authorization from their legal representative." },
          { h: "3. Access", b: "Available on the App Store and Google Play. Users are responsible for device compatibility, connection, and network fees." },
          { h: "4. User account", b: "Sign-in available as anonymous, email/password, Google or Apple. Users must provide accurate information, protect their credentials and not share accounts." },
          { h: "5. Features", b: "Free version with ads and a Supporter version via monthly subscription (ads removed, AI features, premium perks)." },
          { h: "6. AI use", b: "Susumou uses the Google Gemini API for the AI coach, test generation, adapted reading and recommendations. Prompts and anonymized learning data may be transmitted. Users acknowledge AI may produce inaccurate content." },
          { h: "7. Educational limits", b: "Susumou is a learning aid. It is not official teaching, a certification, or a substitute for professional instruction." },
          { h: "8. Prohibited behavior", b: "Misuse, security bypass, server overload, reverse engineering, bots/scripts, account sharing, unauthorized commercial use." },
          { h: "9. Suspension / deletion", b: "SZCZ Softwares may suspend or delete accounts for Terms violations. Users may delete their account via settings or email." },
          { h: "10. Intellectual property", b: "The App, design, code and content are the exclusive property of SZCZ Softwares. Users receive a personal, non-exclusive, revocable license." },
          { h: "11. Liability", b: "Service provided \"as is.\" SZCZ Softwares is not liable for interruptions, bugs, AI errors or exam failures." },
          { h: "12. Updates", b: "Terms may change at any time. Continued use means acceptance." },
          { h: "13. Governing law", b: "French law. French courts have jurisdiction, without prejudice to mandatory EU consumer rights." },
          { h: "14. Contact", b: "SZCZ Softwares (SASU), France. Email: contact@szcz-softwares.com." },
        ],
      },
      ja: {
        title: "利用規約 — Susumou（進もう）",
        updated: "バージョン 1.1 — 最終更新日：2026年3月21日",
        intro: "本利用規約は、SZCZ Softwares（SASU）が提供するモバイルアプリ「Susumou」の利用条件を定めるものです。本アプリをダウンロード・インストールまたは利用することで、本規約に全面的に同意したものとみなされます。",
        sections: [
          { h: "1. 目的", b: "Susumou（進もう）は、SRSフラッシュカード、辞書、JLPTレッスン、AIコーチを組み合わせた日本語学習モバイルアプリです。" },
          { h: "2. 同意", b: "本アプリの利用は本規約への完全な同意を意味します。利用者は必要な法的能力を有する必要があり、未成年者は法定代理人の同意が必要です。" },
          { h: "3. アクセス", b: "App StoreおよびGoogle Playで提供されます。端末の互換性、通信環境、通信費用は利用者の責任となります。" },
          { h: "4. アカウント", b: "匿名、メール／パスワード、Google、Apple Sign-Inでのログインに対応。正確な情報の提供、認証情報の管理、アカウントの共有禁止を遵守してください。" },
          { h: "5. 機能", b: "広告付きの無料版と、月額制のSupporter版（広告削除、AI機能、プレミアム特典）を提供します。" },
          { h: "6. AIの利用", b: "SusumouはAIコーチ、テスト生成、適応読解、レコメンドのためにGoogle Gemini APIを使用します。プロンプトおよび匿名化された学習データが送信される場合があります。AIは不正確な内容を生成する可能性があることをご了承ください。" },
          { h: "7. 学習上の限界", b: "Susumouは学習を補助するツールです。公式教育、資格認定、または専門家による指導の代替ではありません。" },
          { h: "8. 禁止事項", b: "不正利用、セキュリティ回避、サーバー過負荷、リバースエンジニアリング、ボット／スクリプトの使用、アカウント共有、無断の商用利用。" },
          { h: "9. 停止・削除", b: "規約違反があった場合、SZCZ Softwaresはアカウントを停止または削除することがあります。利用者は設定またはメールでアカウントを削除できます。" },
          { h: "10. 知的財産権", b: "本アプリ、デザイン、コード、コンテンツはSZCZ Softwaresの独占的財産です。利用者には個人的・非独占的・取消可能な使用許諾が与えられます。" },
          { h: "11. 責任", b: "サービスは「現状のまま」提供されます。SZCZ Softwaresは中断、バグ、AIエラー、試験不合格について責任を負いません。" },
          { h: "12. 規約の変更", b: "規約はいつでも変更される可能性があります。利用を継続することで変更に同意したものとみなされます。" },
          { h: "13. 準拠法", b: "フランス法に準拠します。EUの強行法規による消費者の権利を妨げない範囲で、フランスの裁判所が管轄を有します。" },
          { h: "14. お問い合わせ", b: "SZCZ Softwares（SASU）、フランス。メール：contact@szcz-softwares.com。" },
        ],
      },
    },
    "cgv": {
      fr: {
        title: "Conditions Générales de Vente — Susumou (進もう)",
        updated: "Version 1.1 — Dernière mise à jour : 21 mars 2026",
        intro: "Les présentes CGV définissent les modalités de souscription et d'utilisation de l'abonnement payant Susumou Supporter, édité par SZCZ Softwares (SASU).",
        sections: [
          { h: "1. Objet", b: "L'abonnement Susumou Supporter donne accès à des fonctionnalités premium dans l'Application." },
          { h: "2. Offre d'abonnement", b: "Suppression des publicités, coach IA personnalisé, génération de tests IA, lectures adaptées, rapports de progression, recommandations d'étude, accès aux futures fonctionnalités premium. Abonnement mensuel." },
          { h: "3. Prix", b: "Prix affiché dans l'Application TTC, en devise locale. Modifiable à tout moment avec notification avant renouvellement." },
          { h: "4. Modalités d'achat", b: "Achats effectués via l'App Store (iOS) ou Google Play (Android). Paiement géré par Apple ou Google. SZCZ Softwares n'a pas accès aux informations bancaires." },
          { h: "5. Durée et renouvellement", b: "Durée mensuelle avec renouvellement automatique, sauf résiliation avant échéance." },
          { h: "6. Résiliation", b: "iOS : Réglages > Abonnements > Susumou > Résilier. Android : Google Play > Abonnements > Susumou > Résilier. Effet à la fin de la période en cours, pas de remboursement au prorata sauf disposition contraire." },
          { h: "7. Droit de rétractation", b: "Conformément à l'article L.221-28 du Code de la consommation, le droit de rétractation ne s'applique pas aux contenus numériques fournis sur support immatériel dont l'exécution a commencé avec l'accord du consommateur." },
          { h: "8. Remboursements", b: "Demandes à adresser directement à la plateforme (Apple : support.apple.com / Google Play : support.google.com). Réclamations : contact@szcz-softwares.com." },
          { h: "9. Accès premium", b: "Accessible via le compte utilisateur associé à l'achat. Les achats restent liés au compte Apple ou Google." },
          { h: "10. Responsabilité", b: "Les fonctionnalités décrites sont fournies sous réserve de la disponibilité du service. SZCZ Softwares ne saurait être tenu responsable d'interruptions ou de dysfonctionnements imputables aux plateformes tierces." },
          { h: "11. Modification", b: "CGV modifiables. Les conditions applicables sont celles en vigueur lors de la souscription ou du renouvellement." },
          { h: "12. Droit applicable", b: "Droit français. Juridictions françaises compétentes." },
          { h: "13. Contact", b: "SZCZ Softwares (SASU), France. E-mail : contact@szcz-softwares.com." },
        ],
      },
      en: {
        title: "Terms of Sale — Susumou (進もう)",
        updated: "Version 1.1 — Last updated: March 21, 2026",
        intro: "These Terms of Sale define the subscription and use of the paid Susumou Supporter subscription, published by SZCZ Softwares (SASU).",
        sections: [
          { h: "1. Purpose", b: "The Susumou Supporter subscription grants access to premium features in the App." },
          { h: "2. Subscription offering", b: "Ad removal, personalized AI coach, AI-generated tests, adapted reading, progress reports, study recommendations, access to future premium features. Monthly subscription." },
          { h: "3. Pricing", b: "Price shown in the App, tax included, in local currency. May change at any time with notice before renewal." },
          { h: "4. Purchase", b: "Purchases are made via the App Store (iOS) or Google Play (Android). Payment handled by Apple or Google. SZCZ Softwares does not access your payment details." },
          { h: "5. Term & renewal", b: "Monthly term with automatic renewal unless canceled before the renewal date." },
          { h: "6. Cancellation", b: "iOS: Settings > Subscriptions > Susumou > Cancel. Android: Google Play > Subscriptions > Susumou > Cancel. Effective at period end, no pro-rata refund unless otherwise required." },
          { h: "7. Right of withdrawal", b: "Under French Consumer Code L.221-28, the right of withdrawal does not apply to digital content whose execution began with consumer consent." },
          { h: "8. Refunds", b: "Requests must be addressed directly to the platform (Apple: support.apple.com / Google Play: support.google.com). Complaints: contact@szcz-softwares.com." },
          { h: "9. Premium access", b: "Accessible via the user account associated with the purchase. Purchases remain linked to your Apple or Google account." },
          { h: "10. Liability", b: "Features are provided subject to service availability. SZCZ Softwares is not liable for interruptions or malfunctions caused by third-party platforms." },
          { h: "11. Updates", b: "Terms may be updated. The applicable terms are those in force at subscription or renewal." },
          { h: "12. Governing law", b: "French law. French courts have jurisdiction." },
          { h: "13. Contact", b: "SZCZ Softwares (SASU), France. Email: contact@szcz-softwares.com." },
        ],
      },
      ja: {
        title: "販売条件 — Susumou（進もう）",
        updated: "バージョン 1.1 — 最終更新日：2026年3月21日",
        intro: "本販売条件は、SZCZ Softwares（SASU）が提供する有料サブスクリプション「Susumou Supporter」の申込みと利用について定めるものです。",
        sections: [
          { h: "1. 目的", b: "Susumou Supporterサブスクリプションは、アプリ内のプレミアム機能へのアクセスを提供します。" },
          { h: "2. サブスクリプション内容", b: "広告削除、パーソナライズドAIコーチ、AI生成テスト、適応読解、進捗レポート、学習推薦、今後のプレミアム機能へのアクセス。月額制。" },
          { h: "3. 価格", b: "アプリ内に表示される価格は税込・現地通貨建てです。更新前に通知のうえ、いつでも変更される可能性があります。" },
          { h: "4. 購入方法", b: "App Store（iOS）またはGoogle Play（Android）経由で購入します。決済はAppleまたはGoogleが処理し、SZCZ Softwaresは決済情報にアクセスしません。" },
          { h: "5. 期間と更新", b: "1か月単位で、更新日前に解約しない限り自動更新されます。" },
          { h: "6. 解約", b: "iOS：設定 > サブスクリプション > Susumou > 解約。Android：Google Play > サブスクリプション > Susumou > 解約。期間終了時に有効となり、法令で定める場合を除き日割返金はありません。" },
          { h: "7. 撤回権", b: "フランス消費法典L.221-28に基づき、消費者の同意のもと履行が開始されたデジタルコンテンツには撤回権が適用されません。" },
          { h: "8. 返金", b: "返金請求は各プラットフォームへ直接行ってください（Apple：support.apple.com／Google Play：support.google.com）。苦情：contact@szcz-softwares.com。" },
          { h: "9. プレミアムアクセス", b: "購入したアカウントに紐付けて利用できます。購入はAppleまたはGoogleアカウントに紐付いたままです。" },
          { h: "10. 責任", b: "機能はサービスの可用性を前提に提供されます。SZCZ Softwaresは第三者プラットフォームによる中断や不具合について責任を負いません。" },
          { h: "11. 規約の変更", b: "条件は更新される可能性があります。適用される条件は、申込みまたは更新時に有効なものです。" },
          { h: "12. 準拠法", b: "フランス法に準拠し、フランスの裁判所が管轄します。" },
          { h: "13. お問い合わせ", b: "SZCZ Softwares（SASU）、フランス。メール：contact@szcz-softwares.com。" },
        ],
      },
    },
    "mentions-legales": {
      fr: {
        title: "Mentions légales — Susumou (進もう)",
        updated: "Dernière mise à jour : avril 2026",
        intro: "Les présentes mentions légales s'appliquent à l'application mobile Susumou et à la communication associée, conformément à la loi n°2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique.",
        sections: [
          { h: "1. Éditeur", b: "SZCZ Softwares (SASU), exploitée par Bastian Niszczota. Siège social : France. E-mail : contact@szcz-softwares.com." },
          { h: "2. Directeur de la publication", b: "Bastian Niszczota, en sa qualité de représentant légal de SZCZ Softwares." },
          { h: "3. Hébergement", b: "Le site et les services backend de l'application sont hébergés par Google Ireland Limited (Firebase Hosting, Cloud Firestore, Cloud Functions), Gordon House, Barrow Street, Dublin 4, Irlande. Région principale : europe-west1." },
          { h: "4. Distribution", b: "L'Application est distribuée via l'App Store (Apple Distribution International, Hollyhill Industrial Estate, Hollyhill, Cork, Irlande) et Google Play (Google Ireland Limited). SZCZ Softwares n'est pas responsable des conditions propres à ces plateformes." },
          { h: "5. Propriété intellectuelle", b: "L'Application Susumou, son code source, sa charte graphique, ses contenus pédagogiques, ses logos et son nom sont la propriété exclusive de SZCZ Softwares, sauf mention contraire. Toute reproduction, représentation ou exploitation sans autorisation écrite est interdite." },
          { h: "6. Marques", b: "« Susumou » et le logo associé sont des marques de SZCZ Softwares. Les marques tierces citées (Apple, Google, Gemini, Firebase, etc.) demeurent la propriété de leurs détenteurs respectifs." },
          { h: "7. Crédits & licences tiers", b: "Données de dictionnaire dérivées de JMdict / EDICT (Electronic Dictionary Research and Development Group, licence Creative Commons Attribution-ShareAlike). Polices et icônes sous licences open source. La liste détaillée est disponible dans l'Application : Paramètres > À propos > Licences." },
          { h: "8. Limitation de responsabilité", b: "SZCZ Softwares met tout en œuvre pour offrir une information fiable, mais ne peut garantir l'exactitude, l'exhaustivité ou l'actualité des contenus pédagogiques générés, notamment par l'IA. L'utilisation de l'Application se fait sous la seule responsabilité de l'utilisateur." },
          { h: "9. Liens externes", b: "L'Application peut contenir des liens vers des sites tiers. SZCZ Softwares n'exerce aucun contrôle sur ces ressources et décline toute responsabilité quant à leur contenu." },
          { h: "10. Données personnelles", b: "Le traitement des données personnelles est détaillé dans la Politique de confidentialité accessible depuis l'Application et sur szczsoftwares.fr/susumou/privacy." },
          { h: "11. Droit applicable", b: "Les présentes mentions sont soumises au droit français. Tout litige relève des juridictions françaises compétentes, sans préjudice des dispositions impératives consommateur de l'Union européenne." },
          { h: "12. Contact", b: "Pour toute question relative aux présentes mentions : SZCZ Softwares — contact@szcz-softwares.com." },
        ],
      },
      en: {
        title: "Legal Notice — Susumou (進もう)",
        updated: "Last updated: April 2026",
        intro: "This legal notice applies to the Susumou mobile application and related communications, in compliance with French Act No. 2004-575 of 21 June 2004 on confidence in the digital economy.",
        sections: [
          { h: "1. Publisher", b: "SZCZ Softwares (SASU), operated by Bastian Niszczota. Registered office: France. Email: contact@szcz-softwares.com." },
          { h: "2. Publishing director", b: "Bastian Niszczota, as legal representative of SZCZ Softwares." },
          { h: "3. Hosting", b: "The site and backend services are hosted by Google Ireland Limited (Firebase Hosting, Cloud Firestore, Cloud Functions), Gordon House, Barrow Street, Dublin 4, Ireland. Primary region: europe-west1." },
          { h: "4. Distribution", b: "The App is distributed via the App Store (Apple Distribution International, Hollyhill Industrial Estate, Hollyhill, Cork, Ireland) and Google Play (Google Ireland Limited). SZCZ Softwares is not responsible for terms specific to these platforms." },
          { h: "5. Intellectual property", b: "The Susumou App, its source code, visual identity, educational content, logos and name are the exclusive property of SZCZ Softwares, unless otherwise stated. Any reproduction, representation or use without written permission is prohibited." },
          { h: "6. Trademarks", b: "\"Susumou\" and its logo are trademarks of SZCZ Softwares. Third-party trademarks cited (Apple, Google, Gemini, Firebase, etc.) remain the property of their respective owners." },
          { h: "7. Third-party credits & licenses", b: "Dictionary data derived from JMdict / EDICT (Electronic Dictionary Research and Development Group, Creative Commons Attribution-ShareAlike). Fonts and icons under open-source licenses. The full list is available in-app: Settings > About > Licenses." },
          { h: "8. Liability", b: "SZCZ Softwares strives to provide reliable information but cannot guarantee the accuracy, completeness or timeliness of educational content, particularly AI-generated content. Use of the App is at the user's sole responsibility." },
          { h: "9. External links", b: "The App may contain links to third-party sites. SZCZ Softwares has no control over these resources and disclaims any liability for their content." },
          { h: "10. Personal data", b: "Personal data processing is detailed in the Privacy Policy available from the App and at szczsoftwares.fr/susumou/privacy." },
          { h: "11. Governing law", b: "This notice is governed by French law. Any dispute falls under the jurisdiction of French courts, without prejudice to mandatory EU consumer rights." },
          { h: "12. Contact", b: "For any question about this notice: SZCZ Softwares — contact@szcz-softwares.com." },
        ],
      },
      ja: {
        title: "法的事項 — Susumou（進もう）",
        updated: "最終更新日：2026年4月",
        intro: "本法的事項は、デジタル経済における信頼に関するフランス法律2004年6月21日第2004-575号に従い、モバイルアプリ「Susumou」および関連するコミュニケーションに適用されます。",
        sections: [
          { h: "1. 発行者", b: "SZCZ Softwares（SASU）、Bastian Niszczotaが運営。本社所在地：フランス。メール：contact@szcz-softwares.com。" },
          { h: "2. 発行責任者", b: "Bastian Niszczota（SZCZ Softwaresの法的代理人として）。" },
          { h: "3. ホスティング", b: "サイトおよびアプリのバックエンドはGoogle Ireland Limited（Firebase Hosting、Cloud Firestore、Cloud Functions、Gordon House, Barrow Street, Dublin 4, Ireland）でホストされています。主要リージョン：europe-west1。" },
          { h: "4. 配布", b: "本アプリはApp Store（Apple Distribution International、Hollyhill Industrial Estate, Hollyhill, Cork, Ireland）およびGoogle Play（Google Ireland Limited）を通じて配布されます。これらプラットフォーム固有の条件についてSZCZ Softwaresは責任を負いません。" },
          { h: "5. 知的財産権", b: "Susumouアプリ、ソースコード、ビジュアルアイデンティティ、教育コンテンツ、ロゴ、名称は、別段の記載がない限りSZCZ Softwaresの独占的財産です。書面による許可なしの複製、公表、利用は禁止されます。" },
          { h: "6. 商標", b: "「Susumou」および関連ロゴはSZCZ Softwaresの商標です。引用される第三者商標（Apple、Google、Gemini、Firebase等）はそれぞれの所有者の財産です。" },
          { h: "7. 第三者クレジット・ライセンス", b: "辞書データはJMdict / EDICT（Electronic Dictionary Research and Development Group、Creative Commons Attribution-ShareAlike）に由来します。フォントおよびアイコンはオープンソースライセンスで提供されています。詳細はアプリ内：設定 > このアプリについて > ライセンスでご確認いただけます。" },
          { h: "8. 責任", b: "SZCZ Softwaresは信頼性のある情報の提供に努めますが、特にAIによって生成された教育コンテンツの正確性、網羅性、最新性は保証されません。本アプリの利用は利用者の自己責任で行われます。" },
          { h: "9. 外部リンク", b: "本アプリには第三者サイトへのリンクが含まれる場合があります。SZCZ Softwaresは当該リソースを管理しておらず、その内容について一切の責任を負いません。" },
          { h: "10. 個人データ", b: "個人データの取扱いについては、アプリ内およびszczsoftwares.fr/susumou/privacyのプライバシーポリシーをご参照ください。" },
          { h: "11. 準拠法", b: "本通知はフランス法に準拠します。EUの強行法規による消費者の権利を妨げない範囲で、フランスの裁判所が管轄を有します。" },
          { h: "12. お問い合わせ", b: "本通知に関するお問い合わせ：SZCZ Softwares — contact@szcz-softwares.com。" },
        ],
      },
    },
    "account-deletion": {
      fr: {
        title: "Suppression de compte — Susumou (進もう)",
        updated: "Version 1.1 — Dernière mise à jour : 21 mars 2026",
        intro: "Conformément au RGPD et aux exigences de l'App Store et de Google Play, vous pouvez à tout moment demander la suppression de votre compte Susumou et de l'ensemble des données personnelles associées.",
        sections: [
          { h: "1. Depuis l'application", b: "Paramètres > Compte > « Supprimer mon compte » > confirmer. Suppression immédiatement prise en compte, traitement complet sous 30 jours." },
          { h: "2. Par e-mail", b: "Envoyer un e-mail à contact@szcz-softwares.com avec l'objet « Suppression de compte Susumou », en précisant l'adresse associée, le type de connexion (e-mail, Google, Apple, anonyme) et toute information permettant d'identifier votre compte. Traitement sous 30 jours." },
          { h: "3. Données supprimées", b: "Authentification (Firebase Auth, e-mail, identifiants Google/Apple), profil et préférences (pseudo, niveau, objectifs), données pédagogiques (progression, SRS, tests), gamification (XP, séries, achievements), documents synchronisés." },
          { h: "4. Données conservées", b: "Données analytiques anonymisées (statistiques agrégées), sauvegardes techniques (jusqu'à 90 jours), historique d'achats in-app (géré par Apple/Google), obligations légales." },
          { h: "5. Délai", b: "Depuis l'application : prise en compte immédiate, suppression complète sous 30 jours. Par e-mail : accusé de réception puis suppression sous 30 jours." },
          { h: "6. Conséquences", b: "La suppression est irréversible. Plus d'accès à la progression, aux achievements ou aux statistiques. Un nouveau compte peut être créé sans restauration." },
          { h: "7. Abonnements actifs", b: "La suppression ne résilie pas automatiquement un abonnement. iOS : Réglages > Abonnements > Susumou > Résilier. Android : Google Play > Abonnements > Susumou > Résilier." },
          { h: "8. Contact", b: "SZCZ Softwares (SASU), France. E-mail : contact@szcz-softwares.com." },
        ],
      },
      en: {
        title: "Account Deletion — Susumou (進もう)",
        updated: "Version 1.1 — Last updated: March 21, 2026",
        intro: "In accordance with the GDPR and App Store / Google Play requirements, you may at any time request the deletion of your Susumou account and associated personal data.",
        sections: [
          { h: "1. From the app", b: "Settings > Account > \"Delete my account\" > confirm. Deletion recorded immediately, full processing within 30 days." },
          { h: "2. By email", b: "Email contact@szcz-softwares.com with subject \"Susumou account deletion,\" including the associated email, sign-in method (email, Google, Apple, anonymous) and any info identifying your account. Processed within 30 days." },
          { h: "3. Data deleted", b: "Authentication (Firebase Auth, email, Google/Apple IDs), profile and preferences (nickname, level, goals), learning data (progress, SRS, tests), gamification (XP, streaks, achievements), synced documents." },
          { h: "4. Data retained", b: "Anonymized analytics (aggregated statistics), technical backups (up to 90 days), in-app purchase history (managed by Apple/Google), legal obligations." },
          { h: "5. Timing", b: "From the app: immediate, full deletion within 30 days. By email: acknowledgment then deletion within 30 days." },
          { h: "6. Consequences", b: "Deletion is irreversible. No more access to progress, achievements or statistics. A new account can be created without restoration." },
          { h: "7. Active subscriptions", b: "Deletion does not automatically cancel a subscription. iOS: Settings > Subscriptions > Susumou > Cancel. Android: Google Play > Subscriptions > Susumou > Cancel." },
          { h: "8. Contact", b: "SZCZ Softwares (SASU), France. Email: contact@szcz-softwares.com." },
        ],
      },
      ja: {
        title: "アカウント削除 — Susumou（進もう）",
        updated: "バージョン 1.1 — 最終更新日：2026年3月21日",
        intro: "GDPRおよびApp Store／Google Playの要件に従い、Susumouのアカウントおよび関連する個人データの削除をいつでもリクエストできます。",
        sections: [
          { h: "1. アプリから削除", b: "設定 > アカウント > 「アカウントを削除する」 > 確認。削除は即座に受付され、30日以内に完了します。" },
          { h: "2. メールから削除", b: "件名「Susumouアカウント削除」とし、登録メールアドレス、ログイン方法（メール／Google／Apple／匿名）、アカウントを特定できる情報を記載してcontact@szcz-softwares.comまでご連絡ください。30日以内に処理します。" },
          { h: "3. 削除されるデータ", b: "認証情報（Firebase Auth、メール、Google／Apple ID）、プロフィールと設定（ニックネーム、レベル、目標）、学習データ（進捗、SRS、テスト）、ゲーミフィケーション（XP、連続記録、実績）、同期されたドキュメント。" },
          { h: "4. 保持されるデータ", b: "匿名化された分析データ（集計統計）、技術的バックアップ（最大90日）、アプリ内購入履歴（Apple／Google管理）、法令上の義務に基づく情報。" },
          { h: "5. 処理時間", b: "アプリから：即時、30日以内に完全削除。メールから：受領確認後、30日以内に削除。" },
          { h: "6. 結果", b: "削除は取り消せません。進捗、実績、統計にはアクセスできなくなります。新規アカウントの作成は可能ですが、復元はできません。" },
          { h: "7. 有効なサブスクリプション", b: "アカウント削除はサブスクリプションを自動解約しません。iOS：設定 > サブスクリプション > Susumou > 解約。Android：Google Play > サブスクリプション > Susumou > 解約。" },
          { h: "8. お問い合わせ", b: "SZCZ Softwares（SASU）、フランス。メール：contact@szcz-softwares.com。" },
        ],
      },
    },
  },
  "soccer-link": {
    "privacy": {
      fr: {
        title: "Politique de confidentialité — Soccer Link",
        updated: "Dernière mise à jour : mars 2026",
        intro: "Soccer Link s'engage à protéger la vie privée de ses utilisateurs. Cette politique explique comment nous collectons, utilisons, stockons et protégeons vos données personnelles lorsque vous utilisez l'Application.",
        sections: [
          { h: "1. Responsable du traitement", b: "Soccer Link. E-mail : privacy@soccerlink.app. Conforme au RGPD et à la loi Informatique et Libertés modifiée." },
          { h: "2. Données collectées", b: "Identification (nom, prénom, e-mail, photo optionnelle, ville). Profil (rôle : joueur, entraîneur, arbitre, dirigeant, parent ; poste, pied, taille ; club actuel ; bio). Utilisation (messages, connexions, activité). Techniques (Firebase Crashlytics, Performance, Analytics anonymisé, modèle d'appareil, OS, version)." },
          { h: "3. Utilisation", b: "Créer et gérer votre compte, permettre la communication, améliorer nos services, envoyer des notifications pertinentes, assurer la sécurité, diagnostiquer les bugs, analyser les performances, respecter nos obligations légales." },
          { h: "4. Base légale", b: "Consentement explicite à l'inscription, exécution du contrat, intérêt légitime (amélioration, sécurité), respect d'obligations légales." },
          { h: "5. Partage et sous-traitants", b: "Certaines infos de profil peuvent être visibles selon vos paramètres. Aucune vente. Sous-traitants : Google Firebase (hébergement, auth, stockage, Analytics, Crashlytics, Performance, Cloud Messaging), Google Sign-In, Algolia SAS (moteur de recherche)." },
          { h: "6. Transferts hors UE", b: "Google peut traiter des données aux États-Unis, encadré par le Data Privacy Framework, les clauses contractuelles types et des mesures complémentaires conformes aux recommandations du CEPD. Algolia traite en UE." },
          { h: "7. Conservation", b: "Compte : tant qu'il est actif. Messages : tant que la conversation existe. Analytics : 14 mois max. Crashs : 90 jours. Logs techniques : 12 mois max. Après suppression : effacement sous 30 jours sauf obligation légale." },
          { h: "8. Vos droits", b: "Accès, rectification, effacement, portabilité, opposition, limitation, retrait du consentement. Contact : privacy@soccerlink.app. Réponse sous 1 mois, prolongeable de 2 mois." },
          { h: "9. Cookies et stockage local", b: "Stockage local pour session, préférences et cache. Firebase Analytics pour données d'utilisation anonymisées, désactivable dans les paramètres." },
          { h: "10. Mineurs", b: "Destinée aux 13 ans et plus. Moins de 18 ans : autorisation parentale. Consentement parental requis en France en dessous de 16 ans. Pas de collecte sciemment en dessous de 13 ans." },
          { h: "11. Modifications", b: "Politique modifiable. Modifications importantes notifiées dans l'Application ; un nouveau consentement peut être demandé." },
          { h: "12. Contact et réclamation", b: "Soccer Link — privacy@soccerlink.app. CNIL : 3 Place de Fontenoy, TSA 80715, 75334 Paris Cedex 07, www.cnil.fr." },
        ],
      },
      en: {
        title: "Privacy Policy — Soccer Link",
        updated: "Last updated: March 2026",
        intro: "Soccer Link is committed to protecting its users' privacy. This policy explains how we collect, use, store and protect your personal data when you use the App.",
        sections: [
          { h: "1. Data controller", b: "Soccer Link. Email: privacy@soccerlink.app. Compliant with the GDPR and the French Data Protection Act." },
          { h: "2. Data collected", b: "Identification (name, email, optional photo, city). Profile (role: player, coach, referee, manager, parent; position, preferred foot, height; current club; bio). Usage (messages, connections, activity). Technical (Firebase Crashlytics, Performance, anonymized Analytics, device model, OS, version)." },
          { h: "3. Use", b: "Create and manage your account, enable communication, improve services, send relevant notifications, ensure security, diagnose bugs, analyze performance, meet legal obligations." },
          { h: "4. Legal basis", b: "Explicit consent at sign-up, contract performance, legitimate interest (improvement, security), legal obligations." },
          { h: "5. Sharing & processors", b: "Some profile info may be visible per your settings. Never sold. Processors: Google Firebase (hosting, auth, storage, Analytics, Crashlytics, Performance, Cloud Messaging), Google Sign-In, Algolia SAS (search)." },
          { h: "6. Transfers outside EU", b: "Google may process data in the US, under the Data Privacy Framework, standard contractual clauses and additional measures per EDPB recommendations. Algolia processes in the EU." },
          { h: "7. Retention", b: "Account: while active. Messages: while the thread exists. Analytics: up to 14 months. Crashes: 90 days. Technical logs: up to 12 months. After deletion: erased within 30 days unless legally required." },
          { h: "8. Your rights", b: "Access, rectification, erasure, portability, objection, restriction, consent withdrawal. Contact: privacy@soccerlink.app. Reply within 1 month, extendable 2 months." },
          { h: "9. Cookies & local storage", b: "Local storage for session, preferences and cache. Firebase Analytics for anonymized usage data, can be disabled in settings." },
          { h: "10. Minors", b: "For ages 13+. Under 18: parental authorization. Parental consent required in France under 16. We do not knowingly collect data under 13." },
          { h: "11. Updates", b: "Policy may be updated. Material changes notified in the App; renewed consent may be requested." },
          { h: "12. Contact & complaints", b: "Soccer Link — privacy@soccerlink.app. CNIL: 3 Place de Fontenoy, TSA 80715, 75334 Paris Cedex 07, www.cnil.fr." },
        ],
      },
      ja: {
        title: "プライバシーポリシー — Soccer Link",
        updated: "最終更新日：2026年3月",
        intro: "Soccer Linkは利用者のプライバシー保護に努めています。本ポリシーは、本アプリの利用にあたり当社がどのように個人データを収集・利用・保管・保護するかを説明します。",
        sections: [
          { h: "1. 管理者", b: "Soccer Link。メール：privacy@soccerlink.app。GDPRおよびフランス情報処理・自由法に準拠します。" },
          { h: "2. 収集するデータ", b: "識別情報（氏名、メール、任意の写真、都市）、プロフィール（ロール：選手・コーチ・審判・運営・保護者、ポジション、利き足、身長、所属クラブ、自己紹介）、利用情報（メッセージ、繋がり、活動）、技術情報（Firebase Crashlytics、Performance、匿名化されたAnalytics、端末モデル、OS、バージョン）。" },
          { h: "3. 利用目的", b: "アカウントの作成・管理、コミュニケーション、サービス改善、関連通知の送信、セキュリティ確保、バグ診断、パフォーマンス分析、法令遵守。" },
          { h: "4. 法的根拠", b: "登録時の明示的な同意、契約の履行、正当な利益（改善・セキュリティ）、法令上の義務。" },
          { h: "5. 共有と委託先", b: "設定に応じて一部のプロフィール情報が他者に表示される場合があります。データを販売することはありません。委託先：Google Firebase（ホスティング、認証、ストレージ、Analytics、Crashlytics、Performance、Cloud Messaging）、Google Sign-In、Algolia SAS（検索）。" },
          { h: "6. EU域外への移転", b: "Googleは米国でデータを処理する場合があり、Data Privacy Framework、標準契約条項、EDPB勧告に基づく追加措置によって保護されています。AlgoliaはEU域内で処理します。" },
          { h: "7. 保存期間", b: "アカウント：有効である間。メッセージ：スレッドが存在する間。Analytics：最長14か月。クラッシュ：90日。技術ログ：最長12か月。削除後：法令上の必要がない限り30日以内に消去。" },
          { h: "8. 利用者の権利", b: "アクセス、訂正、削除、ポータビリティ、異議申立、制限、同意の撤回。連絡先：privacy@soccerlink.app。原則1か月以内に回答、最大2か月まで延長可能です。" },
          { h: "9. Cookieとローカルストレージ", b: "セッション、設定、キャッシュのためにローカルストレージを使用します。匿名化された利用データのためのFirebase Analyticsは設定で無効化できます。" },
          { h: "10. 未成年者", b: "対象年齢は13歳以上です。18歳未満：保護者の同意が必要。フランスでは16歳未満は保護者の同意が必須。13歳未満のデータは意図して収集しません。" },
          { h: "11. ポリシーの変更", b: "ポリシーは更新される可能性があります。重要な変更はアプリ内で通知し、改めて同意を求める場合があります。" },
          { h: "12. お問い合わせと苦情", b: "Soccer Link — privacy@soccerlink.app。CNIL：3 Place de Fontenoy, TSA 80715, 75334 Paris Cedex 07, www.cnil.fr。" },
        ],
      },
    },
    "cgu": {
      fr: {
        title: "Conditions Générales d'Utilisation — Soccer Link",
        updated: "Dernière mise à jour : mars 2026",
        intro: "Les présentes CGU définissent les modalités et conditions d'utilisation de l'application Soccer Link, ainsi que les droits et obligations des parties.",
        sections: [
          { h: "1. Objet", b: "Soccer Link est une application mobile et web permettant aux acteurs du football amateur (joueurs, entraîneurs, arbitres, dirigeants, parents) de se connecter et d'échanger." },
          { h: "2. Description du service", b: "Créer un profil, rechercher et se connecter avec d'autres utilisateurs, rejoindre ou créer des clubs, communiquer via messagerie, consulter et publier des offres, partager des infos sportives. Disponible iOS, Android et web." },
          { h: "3. Inscription et compte", b: "Création par e-mail/mot de passe ou Google Sign-In. Acceptation explicite des CGU et de la politique de confidentialité. Informations exactes, confidentialité des identifiants. Accessible à partir de 13 ans ; moins de 16/18 ans : autorisation du représentant légal." },
          { h: "4. Règles de conduite", b: "Respect des autres utilisateurs, pas de contenu illégal, offensant ou discriminatoire, pas d'usurpation d'identité, pas d'usage commercial non autorisé, pas de compromission de sécurité, pas de collecte des données d'autres utilisateurs, pas de spam, signalement des contenus inappropriés." },
          { h: "5. Notifications push", b: "Notifications pour messages reçus, demandes d'amis et autres événements pertinents. Désactivables à tout moment dans les paramètres." },
          { h: "6. Propriété intellectuelle", b: "L'Application et ses éléments sont la propriété exclusive de Soccer Link. Vos contenus restent votre propriété ; licence non exclusive, gratuite et mondiale accordée à Soccer Link pour le fonctionnement de l'Application, prenant fin à la suppression du contenu ou du compte." },
          { h: "7. Responsabilité", b: "Soccer Link s'efforce d'assurer la disponibilité, sans garantie absolue. Non responsable des contenus publiés par les utilisateurs ni des dommages directs ou indirects liés à l'utilisation." },
          { h: "8. Modification et résiliation", b: "CGU modifiables avec information des utilisateurs ; un nouveau consentement peut être requis. Suppression du compte via paramètres, effacement des données sous 30 jours. Soccer Link peut suspendre un compte en cas de violation." },
          { h: "9. Droit applicable et médiation", b: "Droit français. Recherche amiable avant toute action judiciaire. Médiation de la consommation disponible conformément aux articles L.611-1 et suivants du Code de la consommation." },
          { h: "10. Contact", b: "Soccer Link — contact@soccerlink.app." },
        ],
      },
      en: {
        title: "Terms of Use — Soccer Link",
        updated: "Last updated: March 2026",
        intro: "These Terms of Use define the terms and conditions for using the Soccer Link application, as well as the rights and obligations of the parties.",
        sections: [
          { h: "1. Purpose", b: "Soccer Link is a mobile and web application allowing amateur football stakeholders (players, coaches, referees, managers, parents) to connect and exchange." },
          { h: "2. Service description", b: "Create a profile, search and connect with other users, join or create clubs, message, browse and post opportunities, share sports info. Available on iOS, Android and web." },
          { h: "3. Sign-up & account", b: "Sign up with email/password or Google Sign-In. Explicit acceptance of Terms and Privacy Policy. Accurate information, credential confidentiality. Ages 13+; under 16/18: legal representative's authorization required." },
          { h: "4. Conduct rules", b: "Respect other users, no illegal/offensive/discriminatory content, no impersonation, no unauthorized commercial use, no security compromise, no data scraping, no spam, report inappropriate content." },
          { h: "5. Push notifications", b: "Notifications for received messages, friend requests and other relevant events. Can be disabled at any time in settings." },
          { h: "6. Intellectual property", b: "The App and its elements are the exclusive property of Soccer Link. Your content remains yours; non-exclusive, free, worldwide license to Soccer Link for App operation, ending upon content or account deletion." },
          { h: "7. Liability", b: "Soccer Link strives for availability, no absolute guarantee. Not liable for user-published content or for direct/indirect damages related to use." },
          { h: "8. Changes & termination", b: "Terms may change with user notice; renewed consent may be required. Account deletion via settings, data erased within 30 days. Soccer Link may suspend accounts for violations." },
          { h: "9. Governing law & mediation", b: "French law. Amicable resolution before any legal action. Consumer mediation available under articles L.611-1 et seq. of the French Consumer Code." },
          { h: "10. Contact", b: "Soccer Link — contact@soccerlink.app." },
        ],
      },
      ja: {
        title: "利用規約 — Soccer Link",
        updated: "最終更新日:2026年3月",
        intro: "本利用規約は、Soccer Linkアプリの利用条件と、当事者の権利義務を定めるものです。",
        sections: [
          { h: "1. 目的", b: "Soccer Linkは、アマチュアサッカー関係者（選手、コーチ、審判、運営、保護者）が繋がり交流するためのモバイル／Webアプリです。" },
          { h: "2. サービス概要", b: "プロフィール作成、ユーザー検索・接続、クラブ参加・作成、メッセージ機能、募集の閲覧・投稿、スポーツ情報の共有。iOS、Android、Webで利用可能。" },
          { h: "3. 登録とアカウント", b: "メール／パスワードまたはGoogle Sign-Inで登録。利用規約とプライバシーポリシーへの明示的な同意が必要です。正確な情報、認証情報の秘密保持。対象は13歳以上、16／18歳未満は法定代理人の同意が必要です。" },
          { h: "4. 行動規範", b: "他ユーザーへの敬意、違法・攻撃的・差別的コンテンツの禁止、なりすまし禁止、無断の商用利用禁止、セキュリティ侵害禁止、データの自動収集禁止、スパム禁止、不適切なコンテンツの通報。" },
          { h: "5. プッシュ通知", b: "受信メッセージ、友達リクエスト、その他関連イベントについての通知。設定からいつでも無効にできます。" },
          { h: "6. 知的財産権", b: "本アプリおよびその構成要素はSoccer Linkの独占的財産です。利用者のコンテンツの権利は利用者に帰属しますが、アプリ運営のためにSoccer Linkに非独占的・無償・全世界的なライセンスを付与し、コンテンツまたはアカウント削除時に終了します。" },
          { h: "7. 責任", b: "Soccer Linkは可用性に努めますが絶対的な保証はしません。ユーザー投稿コンテンツや、利用に伴う直接・間接の損害について責任を負いません。" },
          { h: "8. 変更と終了", b: "規約は利用者への通知のうえ変更されることがあり、改めて同意を求める場合があります。設定からアカウント削除可能、データは30日以内に消去されます。違反があった場合、Soccer Linkはアカウントを停止することがあります。" },
          { h: "9. 準拠法と仲介", b: "フランス法に準拠します。法的手続き前に友好的解決を図ります。フランス消費法典L.611-1以下に基づく消費者仲介の利用も可能です。" },
          { h: "10. お問い合わせ", b: "Soccer Link — contact@soccerlink.app。" },
        ],
      },
    },
    "cgv": {
      fr: {
        title: "Conditions Générales de Vente — Soccer Link",
        updated: "Dernière mise à jour : mars 2026",
        intro: "Les présentes CGV s'appliquent à tout achat effectué au sein de l'application Soccer Link.",
        sections: [
          { h: "1. Vendeur", b: "Soccer Link — contact@soccerlink.app." },
          { h: "2. Objet", b: "Vente de produits et services numériques dans l'Application : achats in-app liés à des fonctionnalités premium ou à une visibilité accrue ; abonnements périodiques selon les offres disponibles." },
          { h: "3. Prix", b: "Affichés en EUR ou devise locale, TTC. Prix applicables : ceux en vigueur à la validation. Modifiables à tout moment." },
          { h: "4. Processus d'achat", b: "Via l'App Store (iOS) ou Google Play (Android). Paiement géré par ces plateformes tierces ; Soccer Link n'accède pas aux informations bancaires." },
          { h: "5. Abonnements", b: "Durée déterminée indiquée dans l'Application, renouvellement automatique sauf résiliation avant échéance. Résiliation : iOS via Réglages > Identifiant Apple > Abonnements ; Android via Google Play > Abonnements. Effet en fin de période, pas de remboursement au prorata sauf disposition légale." },
          { h: "6. Droit de rétractation", b: "Non applicable aux contenus numériques fournis sur support immatériel dont l'exécution a commencé avec l'accord du consommateur (article L221-28 du Code de la consommation)." },
          { h: "7. Remboursements", b: "Apple : reportaproblem.apple.com. Google Play : via l'historique des commandes. Réclamations : contact@soccerlink.app." },
          { h: "8. Droit applicable", b: "Droit français. Recherche amiable avant toute procédure judiciaire." },
          { h: "9. Contact", b: "Soccer Link — contact@soccerlink.app." },
        ],
      },
      en: {
        title: "Terms of Sale — Soccer Link",
        updated: "Last updated: March 2026",
        intro: "These Terms of Sale apply to any purchase made within the Soccer Link application.",
        sections: [
          { h: "1. Seller", b: "Soccer Link — contact@soccerlink.app." },
          { h: "2. Purpose", b: "Sale of digital products and services within the App: in-app purchases for premium features or enhanced visibility; periodic subscriptions per the available offers." },
          { h: "3. Pricing", b: "Shown in EUR or local currency, tax included. Applicable prices: those in force at validation. May change at any time." },
          { h: "4. Purchase process", b: "Via the App Store (iOS) or Google Play (Android). Payment handled by those third-party platforms; Soccer Link does not access payment details." },
          { h: "5. Subscriptions", b: "Fixed duration shown in the App, automatic renewal unless canceled before the date. Cancellation: iOS via Settings > Apple ID > Subscriptions; Android via Google Play > Subscriptions. Effective at period end, no pro-rata refund unless legally required." },
          { h: "6. Right of withdrawal", b: "Not applicable to digital content provided on an intangible medium whose execution has begun with the consumer's agreement (French Consumer Code L221-28)." },
          { h: "7. Refunds", b: "Apple: reportaproblem.apple.com. Google Play: via your order history. Complaints: contact@soccerlink.app." },
          { h: "8. Governing law", b: "French law. Amicable resolution before any legal proceedings." },
          { h: "9. Contact", b: "Soccer Link — contact@soccerlink.app." },
        ],
      },
      ja: {
        title: "販売条件 — Soccer Link",
        updated: "最終更新日:2026年3月",
        intro: "本販売条件は、Soccer Linkアプリ内で行われるすべての購入に適用されます。",
        sections: [
          { h: "1. 販売者", b: "Soccer Link — contact@soccerlink.app。" },
          { h: "2. 目的", b: "本アプリ内のデジタル商品・サービスの販売：プレミアム機能や視認性向上のためのアプリ内購入、提供中のオファーに基づく定期サブスクリプション。" },
          { h: "3. 価格", b: "ユーロまたは現地通貨建てで税込表示。適用価格は決済時点で有効なものです。いつでも変更される可能性があります。" },
          { h: "4. 購入手続き", b: "App Store（iOS）またはGoogle Play（Android）経由。決済は当該第三者プラットフォームが処理し、Soccer Linkは決済情報にアクセスしません。" },
          { h: "5. サブスクリプション", b: "アプリ内に表示される所定の期間で自動更新されます。期日前に解約しない限り更新されます。解約：iOSは設定 > Apple ID > サブスクリプションから。Androidは Google Play > サブスクリプションから。期間終了時に有効、法令で定める場合を除き日割返金はありません。" },
          { h: "6. 撤回権", b: "消費者の同意のもと履行が開始された無形デジタルコンテンツには適用されません（フランス消費法典L221-28）。" },
          { h: "7. 返金", b: "Apple：reportaproblem.apple.com。Google Play：注文履歴から。苦情：contact@soccerlink.app。" },
          { h: "8. 準拠法", b: "フランス法に準拠。法的手続き前に友好的解決を図ります。" },
          { h: "9. お問い合わせ", b: "Soccer Link — contact@soccerlink.app。" },
        ],
      },
    },
    "mentions-legales": {
      fr: {
        title: "Mentions légales — Soccer Link",
        updated: "Dernière mise à jour : avril 2026",
        intro: "Les présentes mentions légales s'appliquent à l'application Soccer Link et à ses sites associés, conformément à la loi n°2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique.",
        sections: [
          { h: "1. Éditeur", b: "Soccer Link, exploitée par SZCZ Softwares (SASU), Bastian Niszczota. Siège social : France. E-mail : contact@soccerlink.app." },
          { h: "2. Directeur de la publication", b: "Bastian Niszczota, en sa qualité de représentant légal." },
          { h: "3. Hébergement", b: "Application et services backend hébergés par Google Ireland Limited (Firebase Hosting, Cloud Firestore, Cloud Functions, Cloud Storage), Gordon House, Barrow Street, Dublin 4, Irlande. Moteur de recherche fourni par Algolia SAS, 55 rue d'Amsterdam, 75008 Paris, France." },
          { h: "4. Distribution", b: "L'Application est disponible via l'App Store (Apple Distribution International, Hollyhill Industrial Estate, Hollyhill, Cork, Irlande), Google Play (Google Ireland Limited) et le web. Soccer Link n'est pas responsable des conditions propres à ces plateformes." },
          { h: "5. Propriété intellectuelle", b: "L'Application Soccer Link, son code, sa charte graphique, ses logos, son nom et l'ensemble de ses contenus sont la propriété exclusive de Soccer Link, sauf mention contraire. Toute reproduction non autorisée est interdite." },
          { h: "6. Marques", b: "« Soccer Link » et le logo associé sont des marques de Soccer Link. Les marques tierces (Apple, Google, Algolia, Firebase, etc.) demeurent la propriété de leurs détenteurs respectifs." },
          { h: "7. Contenus utilisateurs", b: "Les utilisateurs conservent la propriété des contenus qu'ils publient. Conformément aux CGU, ils accordent à Soccer Link une licence d'utilisation strictement limitée au fonctionnement du service." },
          { h: "8. Crédits & licences tiers", b: "Polices, icônes et bibliothèques sous licences open source. La liste détaillée est disponible dans l'Application : Paramètres > À propos > Licences." },
          { h: "9. Limitation de responsabilité", b: "Soccer Link s'efforce d'assurer la disponibilité du service, sans en garantir l'absence d'interruption ou d'erreur. Soccer Link ne saurait être tenu responsable des contenus publiés par les utilisateurs ni des dommages directs ou indirects liés à l'utilisation de l'Application." },
          { h: "10. Liens externes", b: "L'Application peut renvoyer vers des ressources tierces sur lesquelles Soccer Link n'exerce aucun contrôle et décline toute responsabilité." },
          { h: "11. Données personnelles", b: "Le traitement des données personnelles est détaillé dans la Politique de confidentialité disponible depuis l'Application et sur szczsoftwares.fr/soccer-link/privacy." },
          { h: "12. Droit applicable", b: "Les présentes mentions sont soumises au droit français. Tout litige relève des juridictions françaises compétentes, sans préjudice des dispositions impératives consommateur de l'Union européenne." },
          { h: "13. Contact", b: "Soccer Link — contact@soccerlink.app." },
        ],
      },
      en: {
        title: "Legal Notice — Soccer Link",
        updated: "Last updated: April 2026",
        intro: "This legal notice applies to the Soccer Link application and its associated sites, in compliance with French Act No. 2004-575 of 21 June 2004 on confidence in the digital economy.",
        sections: [
          { h: "1. Publisher", b: "Soccer Link, operated by SZCZ Softwares (SASU), Bastian Niszczota. Registered office: France. Email: contact@soccerlink.app." },
          { h: "2. Publishing director", b: "Bastian Niszczota, as legal representative." },
          { h: "3. Hosting", b: "App and backend services hosted by Google Ireland Limited (Firebase Hosting, Cloud Firestore, Cloud Functions, Cloud Storage), Gordon House, Barrow Street, Dublin 4, Ireland. Search engine provided by Algolia SAS, 55 rue d'Amsterdam, 75008 Paris, France." },
          { h: "4. Distribution", b: "The App is available via the App Store (Apple Distribution International, Hollyhill Industrial Estate, Hollyhill, Cork, Ireland), Google Play (Google Ireland Limited) and on the web. Soccer Link is not responsible for terms specific to these platforms." },
          { h: "5. Intellectual property", b: "The Soccer Link App, its code, visual identity, logos, name and all of its content are the exclusive property of Soccer Link, unless otherwise stated. Any unauthorized reproduction is prohibited." },
          { h: "6. Trademarks", b: "\"Soccer Link\" and its logo are trademarks of Soccer Link. Third-party trademarks (Apple, Google, Algolia, Firebase, etc.) remain the property of their respective owners." },
          { h: "7. User content", b: "Users retain ownership of the content they post. Under the Terms of Use, they grant Soccer Link a license strictly limited to operating the service." },
          { h: "8. Third-party credits & licenses", b: "Fonts, icons and libraries under open-source licenses. The full list is available in-app: Settings > About > Licenses." },
          { h: "9. Liability", b: "Soccer Link strives to ensure service availability without guaranteeing the absence of interruptions or errors. Soccer Link cannot be held liable for content published by users or for direct or indirect damages related to use of the App." },
          { h: "10. External links", b: "The App may link to third-party resources over which Soccer Link has no control and disclaims any liability." },
          { h: "11. Personal data", b: "Personal data processing is detailed in the Privacy Policy available from the App and at szczsoftwares.fr/soccer-link/privacy." },
          { h: "12. Governing law", b: "This notice is governed by French law. Any dispute falls under the jurisdiction of French courts, without prejudice to mandatory EU consumer rights." },
          { h: "13. Contact", b: "Soccer Link — contact@soccerlink.app." },
        ],
      },
      ja: {
        title: "法的事項 — Soccer Link",
        updated: "最終更新日：2026年4月",
        intro: "本法的事項は、デジタル経済における信頼に関するフランス法律2004年6月21日第2004-575号に従い、Soccer Linkアプリおよび関連サイトに適用されます。",
        sections: [
          { h: "1. 発行者", b: "Soccer Link（SZCZ Softwares（SASU）、Bastian Niszczotaが運営）。本社所在地：フランス。メール：contact@soccerlink.app。" },
          { h: "2. 発行責任者", b: "Bastian Niszczota（法的代理人として）。" },
          { h: "3. ホスティング", b: "アプリおよびバックエンドはGoogle Ireland Limited（Firebase Hosting、Cloud Firestore、Cloud Functions、Cloud Storage、Gordon House, Barrow Street, Dublin 4, Ireland）でホストされています。検索エンジンはAlgolia SAS（55 rue d'Amsterdam, 75008 Paris, France）が提供します。" },
          { h: "4. 配布", b: "本アプリはApp Store（Apple Distribution International、Hollyhill Industrial Estate, Hollyhill, Cork, Ireland）、Google Play（Google Ireland Limited）、およびWebで提供されます。これらプラットフォーム固有の条件についてSoccer Linkは責任を負いません。" },
          { h: "5. 知的財産権", b: "Soccer Linkアプリ、コード、ビジュアルアイデンティティ、ロゴ、名称、ならびにすべてのコンテンツは、別段の記載がない限りSoccer Linkの独占的財産です。無断複製は禁じられています。" },
          { h: "6. 商標", b: "「Soccer Link」および関連ロゴはSoccer Linkの商標です。第三者商標（Apple、Google、Algolia、Firebase等）は各所有者の財産です。" },
          { h: "7. ユーザーコンテンツ", b: "投稿コンテンツの所有権はユーザーに帰属します。利用規約に基づき、サービス運営に厳密に必要な範囲でSoccer Linkにライセンスを許諾します。" },
          { h: "8. 第三者クレジット・ライセンス", b: "フォント、アイコン、ライブラリはオープンソースライセンスで提供されています。詳細はアプリ内：設定 > このアプリについて > ライセンスでご確認いただけます。" },
          { h: "9. 責任", b: "Soccer Linkはサービスの可用性確保に努めますが、中断や誤りの不在を保証するものではありません。ユーザー投稿コンテンツや、利用に関連する直接・間接の損害について責任を負いません。" },
          { h: "10. 外部リンク", b: "本アプリには第三者リソースへのリンクが含まれる場合があります。Soccer Linkは当該リソースを管理しておらず、その内容について責任を負いません。" },
          { h: "11. 個人データ", b: "個人データの取扱いについては、アプリ内およびszczsoftwares.fr/soccer-link/privacyのプライバシーポリシーをご参照ください。" },
          { h: "12. 準拠法", b: "本通知はフランス法に準拠します。EUの強行法規による消費者の権利を妨げない範囲で、フランスの裁判所が管轄を有します。" },
          { h: "13. お問い合わせ", b: "Soccer Link — contact@soccerlink.app。" },
        ],
      },
    },
    "account-deletion": {
      fr: {
        title: "Suppression de compte — Soccer Link",
        updated: "Dernière mise à jour : mars 2026",
        intro: "Conformément au RGPD et aux exigences de l'App Store et de Google Play, vous pouvez à tout moment demander la suppression de votre compte Soccer Link et de l'ensemble des données personnelles associées.",
        sections: [
          { h: "1. Depuis l'application", b: "Paramètres > Compte > « Supprimer mon compte » > confirmer. Votre compte et vos données sont supprimés." },
          { h: "2. Par e-mail", b: "Envoyer un e-mail à privacy@soccerlink.app avec l'objet « Suppression de compte Soccer Link », en précisant l'adresse associée et votre nom d'utilisateur si connu. Traitement sous 30 jours max, avec confirmation." },
          { h: "3. Données supprimées", b: "Profil (nom, photo, bio, localisation, rôle, données spécifiques), données sociales (amis, demandes, connexions), messages et conversations, appartenance aux clubs, index de recherche Algolia, données d'authentification Firebase Auth, fichiers Firebase Storage." },
          { h: "4. Données conservées", b: "Analytics anonymisés (politique Firebase Analytics), données de facturation (obligations légales), rapports de crash anonymisés (amélioration du service)." },
          { h: "5. Conséquences", b: "Suppression irréversible. Votre profil n'est plus visible. Les messages dans des conversations existantes peuvent être supprimés ou anonymisés. Si abonnement actif, résilier manuellement au préalable." },
          { h: "6. Contact", b: "Soccer Link — privacy@soccerlink.app." },
        ],
      },
      en: {
        title: "Account Deletion — Soccer Link",
        updated: "Last updated: March 2026",
        intro: "In accordance with the GDPR and App Store / Google Play requirements, you may at any time request the deletion of your Soccer Link account and associated personal data.",
        sections: [
          { h: "1. From the app", b: "Settings > Account > \"Delete my account\" > confirm. Your account and data are deleted." },
          { h: "2. By email", b: "Email privacy@soccerlink.app with subject \"Soccer Link account deletion,\" providing the associated email and your username if known. Processed within 30 days max, with confirmation." },
          { h: "3. Data deleted", b: "Profile (name, photo, bio, location, role, specific data), social data (friends, requests, connections), messages and conversations, club memberships, Algolia search index, Firebase Auth data, Firebase Storage files." },
          { h: "4. Data retained", b: "Anonymized analytics (Firebase Analytics policy), billing data (legal obligations), anonymized crash reports (service improvement)." },
          { h: "5. Consequences", b: "Deletion is irreversible. Your profile is no longer visible. Messages in existing conversations may be deleted or anonymized. If you have an active subscription, cancel it manually first." },
          { h: "6. Contact", b: "Soccer Link — privacy@soccerlink.app." },
        ],
      },
      ja: {
        title: "アカウント削除 — Soccer Link",
        updated: "最終更新日:2026年3月",
        intro: "GDPRおよびApp Store／Google Playの要件に従い、Soccer Linkのアカウントおよび関連する個人データの削除をいつでもリクエストできます。",
        sections: [
          { h: "1. アプリから削除", b: "設定 > アカウント > 「アカウントを削除する」 > 確認。アカウントとデータが削除されます。" },
          { h: "2. メールから削除", b: "件名「Soccer Linkアカウント削除」とし、登録メールアドレスと、わかればユーザー名を記載してprivacy@soccerlink.appまでご連絡ください。最長30日以内に処理し、完了をご連絡します。" },
          { h: "3. 削除されるデータ", b: "プロフィール（氏名、写真、自己紹介、所在地、ロール、固有データ）、ソーシャルデータ（友達、リクエスト、繋がり）、メッセージと会話、クラブ所属、Algolia検索インデックス、Firebase Auth情報、Firebase Storageのファイル。" },
          { h: "4. 保持されるデータ", b: "匿名化された分析データ（Firebase Analyticsポリシー）、請求データ（法令上の義務）、匿名化されたクラッシュレポート（サービス改善）。" },
          { h: "5. 結果", b: "削除は取り消せません。プロフィールは表示されなくなります。既存の会話内のメッセージは削除または匿名化される場合があります。有効なサブスクリプションがある場合は、事前に手動で解約してください。" },
          { h: "6. お問い合わせ", b: "Soccer Link — privacy@soccerlink.app。" },
        ],
      },
    },
  },
};

Object.assign(window, {
  PROJECTS, SERVICES, STACK, STATS, COPY, CATEGORY_META, PROJECT_LEGAL,
  Cursor, Prompt, Tag, StatusDot, AsciiRule, Placeholder, tx,
});
